---
- name: Install and start docker.io
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install docker.io package
      apt:
        name: docker.io
        state: present

    - name: Ensure docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Show Docker version
      shell: docker --version
      register: docker_version

    - name: Print Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
