---
- name: Install and verify Docker
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Start Docker manually (if systemd is not available)
      shell: |
        if ! pgrep dockerd; then
          nohup dockerd > /var/log/dockerd.log 2>&1 &
        fi
      async: 30
      poll: 0

    - name: Wait for Docker daemon to be ready
      wait_for:
        port: 2375
        delay: 5
        timeout: 30
      ignore_errors: yes

    - name: Run hello-world container to verify Docker
      shell: docker run hello-world
      register: hello_output
      ignore_errors: yes

    - name: Show Docker output
      debug:
        var: hello_output.stdout
